### ISSUE TITLE
Unable to find directive

### ISSUE THREAD

**Issue by bettsjj** [alcoceba/ngCarouselDirective#8]
Android Build issue after upgrading Nativescript (tns --version = 4.0.0)  and angular 5.2.0 versions

rg.nativescript.am2pro8/com.tns.NativeScriptActivity
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error: com.tns.NativeScriptException: Failed to find module: "./nativescript-ng2-carousel.directive", relative to: app/tns_modules/nativescript-ng2-carousel/

**Comment by gamalgogo** [comment]
+1

**Comment by ajayrcdev** [comment]
same in ns angular

**Comment by suisseworks** [comment]
+1

**Comment by JCAguilera** [comment]
+1 Same error

**Comment by leosilvestre7** [comment]
same problem

**Comment by sanjay-patel** [comment]
Same path error

Error: com.tns.NativeScriptException: Failed to find module: "./nativescript-ng2-carousel.directive", relative to: app/tns_modules/nativescript-ng2-carousel/

**Comment by alcoceba** [comment]
The problem is that one of the files is not transpyling to Javascript, as a result "Failed to find module: ./nativescript-ng2-carousel.directive" is thrown.

I'm trying to fix this, if anyone resolved it before, please, let me know.

**Comment by alcoceba** [comment]
It should compile now (last relese version is 0.1.0) with Angular 6 & Nativescript 4, but it should work with previous versions.

Furthermore, I've deleted the "demo" folder in this repoitory and I've moved it to another one, so that I think it didn't make no sense to have it here and it prevents form getting some app submission errors. 

You can check it out the demo here if you want:

https://github.com/alcoceba/ngCarouselDirective

Let me know if you keep having trouble with this release. 

Thank you for your feedback.
