### ISSUE TITLE
Demo app is installed in node-modules

### ISSUE THREAD

**Issue by lin-brian-l** [alcoceba/ngCarouselDirective#9]
We are using this package in our app and our most recent push to iTunes was rejected because "the bundle at '/Payload/<app name>/app/tns_modules/nativescript-ng2-carousel/demo/app/App_Resources/iOS/Info.plist' does not contain a bundle executable". Upon further investigation, we found that (1) the `nativescript-ng2-carousel` directory in our `node-modules` folder contained a `demo` directory with `app` files and that (2) there is a `.npmignore` file, but it specifies specific files and folders within the `demo` directory instead of excluding the `demo` directory as a whole. We have not verified that deleting the `demo` directory from the plugin in our `node-modules` folder will solve our issue, but you may want to consider editing your `.npmignore` file.

**Comment by alcoceba** [comment]
I've deleted the "demo" folder in this repoitory and I've moved it to another one, so that I think it didn't make no sense to have it here and it prevents form getting some app submission errors. So that, it should work now.

You can check it out the demo here if you want:

https://github.com/alcoceba/ngCarouselDirective

Let me know if you keep having trouble with this release. 

Thank you for your feedback.
